[project]
name = 'genomic-chain-stacks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.compliance]
path = 'contracts/compliance.clar'
clarity_version = 4
epoch = 'latest'

[contracts.genetic-data]
path = 'contracts/genetic-data.clar'
clarity_version = 4
epoch = 'latest'

[contracts.genetic-data-trait]
path = 'contracts/genetic-data-trait.clar'
clarity_version = 4
epoch = 'latest'

[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 4
epoch = 'latest'

[contracts.verification]
path = 'contracts/verification.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
